import { useMemo, useState } from "react";
import {
  ArrowRight, BellRinging, Buildings, CalendarBlank, ChartLineUp,
  CheckCircle, CheckSquare, ClipboardText, ClockCountdown, Database, Envelope,
  Factory, FileText, FlagCheckered, Gauge, GitCommit, LockKey, Play, Printer,
  RocketLaunch, ShieldCheck, Sparkle, TrendUp, UserGear, UsersThree, Warning,
  WhatsappLogo, XCircle
} from "@phosphor-icons/react";
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart,
  ResponsiveContainer, Tooltip, XAxis, YAxis
} from "recharts";

const trend = [
  {day:"12 jun",health:61,delivery:54},{day:"17 jun",health:64,delivery:58},
  {day:"22 jun",health:62,delivery:61},{day:"27 jun",health:67,delivery:64},
  {day:"02 jul",health:70,delivery:68},{day:"07 jul",health:66,delivery:71},
  {day:"11 jul",health:68,delivery:73}
];

const departments = [
  ["COM","Comercial / Concept","André Mota",74,66,1],["PMO","PMO","Rodrigo Baruco",91,78,2],
  ["PCP","PCP","Weslley Silva",86,72,2],["CMP","Compras / Importação","Claudia Duarte",103,61,3],
  ["EMC","Eng. Mecânica","Gustavo Pereira",94,69,2],["EEL","Eng. Elétrica","Gustavo Pereira",88,64,1],
  ["PRD","Produção","Flavio Moreno",82,70,1],["MON","Montagem","Rojekson Souza",83,57,1],
  ["INF","Infraestrutura","Douglas Alves",112,65,4],["ESP","Espec. de Software","Douglas Alves",78,62,1],
  ["WCS","WCS Velox","Marcelo Sanches",98,73,2],["IMP","Implantação","Douglas Alves",108,68,3],
  ["PLC","PLC","Gustavo Pereira",117,71,4],["PÓS","Pós-vendas","Caique Fracaro",63,82,0]
].map(([code,name,owner,load,progress,blocked])=>({code,name,owner,load,progress,blocked}));

const actionsSeed = [
  {id:1,p:"P0",project:"TITANO",task:"Normalizar falha do Sensor X e anexar telemetria",owner:"Rodrigo Baruco",due:"Hoje · 18:00",status:"Em ação"},
  {id:2,p:"P1",project:"MARKET PERU",task:"Confirmar range IP /24 e VPN site-to-site",owner:"Ivan",due:"Hoje · 16:00",status:"Aguardando"},
  {id:3,p:"P1",project:"NAVEPARK",task:"Fechar topologia das VMs Oracle KVM",owner:"Daiana Costa",due:"12 jul",status:"Em andamento"},
  {id:4,p:"P2",project:"QUELUZ",task:"Consolidar evidências para o GL1",owner:"Matheus",due:"15 jul",status:"Não iniciado"},
  {id:5,p:"P2",project:"BP",task:"Confirmar equipe de campo para Go Live",owner:"Giovanni",due:"18 jul",status:"Não iniciado"}
];

const blockers = [
  {project:"MARKET PERU",area:"INF · Cliente",age:"12 dias",impact:"Infra de testes sem condição de homologação",owner:"Ivan",action:"Escalar arquitetura e fechar IP/VPN até 12/07."},
  {project:"NAVEPARK",area:"EMC · INF",age:"8 dias",impact:"Ambiente HML ameaça o Go Live de setembro",owner:"Daiana",action:"Validar VMs e registrar decisão técnica até 14/07."},
  {project:"TITANO",area:"CMP · PLC",age:"2 horas",impact:"Sensor físico interrompe sequência de testes",owner:"Baruco",action:"Trocar sensor, testar 20 ciclos e anexar evidência."}
];

const riskItems = [
  {id:"R-18",kind:"Risco",title:"Atraso na aquisição de hardware crítico",project:"TITANO",prob:4,impact:5,owner:"Claudia Duarte",response:"Mitigar",due:"12 jul"},
  {id:"I-09",kind:"Impedimento",title:"VPN e range IP não confirmados",project:"MARKET PERU",prob:5,impact:4,owner:"Ivan",response:"Escalar",due:"Hoje"},
  {id:"A-07",kind:"Premissa",title:"Cliente libera VMs até 14/07",project:"NAVEPARK",prob:3,impact:4,owner:"Daiana",response:"Validar",due:"14 jul"},
  {id:"D-04",kind:"Dependência",title:"GL1 depende da homologação do ambiente",project:"QUELUZ",prob:3,impact:3,owner:"Matheus",response:"Monitorar",due:"18 jul"},
  {id:"R-21",kind:"Risco",title:"Capacidade PLC acima do limite em setembro",project:"PORTFÓLIO",prob:4,impact:4,owner:"Baruco",response:"Replanejar",due:"15 jul"}
];

function Panel({title,subtitle,children,className=""}){
  return <article className={`foundation-panel ${className}`}><div className="foundation-title"><div><b>{title}</b><span>{subtitle}</span></div></div>{children}</article>;
}

function Metric({icon:Icon,label,value,note,tone="cyan"}){
  return <article className={`foundation-metric ${tone}`}><Icon/><span><small>{label}</small><b>{value}</b><em>{note}</em></span></article>;
}

export function ExecutiveDashboard({projects,setActive}){
  const health=Math.round(projects.reduce((sum,p)=>sum+p.health,0)/projects.length);
  return <section className="page foundation-page">
    <div className="executive-hero">
      <div className="health-visual"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={[{v:health},{v:100-health}]} dataKey="v" startAngle={90} endAngle={-270} innerRadius={55} outerRadius={67} stroke="none"><Cell fill="#f5c300"/><Cell fill="#18263a"/></Pie></PieChart></ResponsiveContainer><span><small>HEALTH SCORE</small><b>{health}</b><em>/100</em></span></div>
      <div className="executive-brief"><small>BRIEFING EXECUTIVO · 11 JUL 2026</small><h2>Hoje, a operação precisa de três decisões.</h2><p>O portfólio está estável, mas <b>Infraestrutura, Compras e PLC</b> concentram os riscos que podem deslocar os próximos Go Lives. Priorize Market Peru, estabilize o Sensor X do TITANO e confirme as VMs do Navepark.</p><div><button className="primary" onClick={()=>setActive("action")}><CheckSquare/>Abrir plano de ação</button><button className="ghost" onClick={()=>setActive("executive")}><FileText/>Ver one-page</button></div></div>
      <div className="countdown"><small>PRÓXIMO GO LIVE</small><b>9</b><span>dias</span><strong>TITANO · 20 JUL</strong><em>78% de confiança</em></div>
    </div>
    <div className="foundation-metrics"><Metric icon={Buildings} label="CARTEIRA" value={`${projects.length} projetos`} note="2 bloqueados"/><Metric icon={Warning} label="RISCO MATERIAL" value="R$ 1,8 mi" note="exposição estimada" tone="red"/><Metric icon={UsersThree} label="CAPACIDADE" value="117% PLC" note="pico em setembro" tone="yellow"/><Metric icon={FlagCheckered} label="GO LIVES" value="4 em 90d" note="2 confirmados" tone="green"/></div>
    <div className="foundation-grid two-one"><Panel title="Quem o COO deve cobrar hoje" subtitle="Priorização calculada por impacto, prazo e SLA"><div className="charge-list">{blockers.map((b,i)=><button key={b.project} onClick={()=>setActive(i===2?"alerts":"action")}><strong>0{i+1}</strong><span><b>{b.project}</b><small>{b.action}</small></span><em>{b.owner}</em><ArrowRight/></button>)}</div></Panel><Panel title="Pulso do portfólio" subtitle="Tendência dos últimos 30 dias"><div className="foundation-chart"><ResponsiveContainer><AreaChart data={trend}><defs><linearGradient id="healthFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#28c5e7" stopOpacity=".35"/><stop offset="1" stopColor="#28c5e7" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#17243a" vertical={false}/><XAxis dataKey="day" tick={{fontSize:9}} stroke="#66758c"/><YAxis domain={[40,100]} tick={{fontSize:9}} stroke="#66758c"/><Tooltip/><Area dataKey="health" stroke="#28c5e7" fill="url(#healthFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel></div>
  </section>;
}

export function ActionCenter({notify}){
  const [actions,setActions]=useState(actionsSeed); const [filter,setFilter]=useState("Todos");
  const shown=filter==="Todos"?actions:actions.filter(a=>a.p===filter);
  const finish=id=>{setActions(actions.map(a=>a.id===id?{...a,status:"Concluído"}:a));notify("Atividade concluída com evidência pendente de auditoria.")};
  return <section className="page foundation-page"><div className="foundation-metrics"><Metric icon={BellRinging} label="AÇÃO IMEDIATA" value="1 P0" note="SLA em curso" tone="red"/><Metric icon={ClockCountdown} label="VENCEM HOJE" value="2 tarefas" note="1 externa" tone="yellow"/><Metric icon={CheckCircle} label="CONCLUÍDAS" value={`${actions.filter(a=>a.status==="Concluído").length}/5`} note="no ciclo atual" tone="green"/><Metric icon={UsersThree} label="SEM RESPONSÁVEL" value="0" note="governança íntegra"/></div>
    <div className="action-toolbar"><div><h2>O que precisa acontecer agora</h2><p>Fila única de cobrança com prioridade, dono, prazo e evidência.</p></div><div>{["Todos","P0","P1","P2"].map(x=><button className={filter===x?"active":""} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>
    <div className="action-board">{shown.map(a=><article key={a.id} className={`action-item ${a.p.toLowerCase()}`}><span className="priority-pill">{a.p}</span><div><small>{a.project}</small><h3>{a.task}</h3><span><UsersThree/>{a.owner}<CalendarBlank/>{a.due}</span></div><em>{a.status}</em><button disabled={a.status==="Concluído"} onClick={()=>finish(a.id)}><CheckCircle/>{a.status==="Concluído"?"Concluída":"Concluir"}</button></article>)}</div>
  </section>;
}

export function ManagementPage(){
  return <section className="page foundation-page"><div className="foundation-metrics"><Metric icon={Gauge} label="SAÚDE MÉDIA" value="68/100" note="+7 em 30 dias" tone="green"/><Metric icon={TrendUp} label="ENTREGA" value="73%" note="+19 p.p."/><Metric icon={Warning} label="GARGALOS" value="3 ativos" note="23 dias acumulados" tone="red"/><Metric icon={ClockCountdown} label="PREVISIBILIDADE" value="81%" note="marcos no prazo" tone="yellow"/></div><div className="foundation-grid equal"><Panel title="Tendência de performance · 30 dias" subtitle="Saúde e entrega com base nas evidências registradas"><div className="foundation-chart large"><ResponsiveContainer><AreaChart data={trend}><CartesianGrid stroke="#17243a" vertical={false}/><XAxis dataKey="day" tick={{fontSize:9}} stroke="#66758c"/><YAxis domain={[40,100]} tick={{fontSize:9}} stroke="#66758c"/><Tooltip/><Area dataKey="health" name="Saúde" stroke="#28c5e7" fill="#28c5e722" strokeWidth={2}/><Area dataKey="delivery" name="Entrega" stroke="#f5c300" fill="#f5c30012" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Capacidade por área crítica" subtitle="Acima de 100% exige replanejamento"><div className="foundation-chart large"><ResponsiveContainer><BarChart data={departments.filter(d=>d.load>=90)} layout="vertical"><CartesianGrid stroke="#17243a" horizontal={false}/><XAxis type="number" domain={[0,130]} tick={{fontSize:9}} stroke="#66758c"/><YAxis dataKey="code" type="category" tick={{fontSize:9}} stroke="#66758c" width={35}/><Tooltip/><Bar dataKey="load" name="Carga %" radius={[0,4,4,0]}>{departments.filter(d=>d.load>=90).map(d=><Cell key={d.code} fill={d.load>100?"#fb5470":"#28c5e7"}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel></div><Panel title="Gargalos ativos" subtitle="Texto completo para orientar cobrança, não apenas um semáforo"><div className="blocker-table"><header><span>Projeto / área</span><span>Impacto operacional</span><span>Próxima ação obrigatória</span><span>Dono / idade</span></header>{blockers.map(b=><div key={b.project}><span><b>{b.project}</b><small>{b.area}</small></span><p>{b.impact}</p><p>{b.action}</p><span><b>{b.owner}</b><small>{b.age}</small></span></div>)}</div></Panel></section>;
}

export function AnalyticsPage(){
  const commitDays=Array.from({length:84},(_,i)=>({i,v:(i*7+i%5*3)%5}));
  return <section className="page foundation-page"><div className="foundation-grid thirds"><Panel title="Saúde do portfólio" subtitle="Distribuição dos projetos"><div className="donut-wrap"><div className="donut"><ResponsiveContainer><PieChart><Pie data={[{n:"Saudável",v:2},{n:"Atenção",v:2},{n:"Crítico",v:2}]} dataKey="v" innerRadius={48} outerRadius={70} stroke="none"><Cell fill="#40d986"/><Cell fill="#f5c300"/><Cell fill="#fb5470"/></Pie><Tooltip/></PieChart></ResponsiveContainer><span><b>6</b><small>projetos</small></span></div><ul><li><i className="green"/>Saudáveis <b>2</b></li><li><i className="yellow"/>Atenção <b>2</b></li><li><i className="red"/>Críticos <b>2</b></li></ul></div></Panel><Panel title="Qualidade da evidência" subtitle="Confiabilidade do progresso calculado"><div className="score-gauge"><b>82%</b><span>ALTA CONFIANÇA</span><i><em style={{width:"82%"}}/></i><p>91% dos itens concluídos possuem evidência auditável e origem identificada.</p></div></Panel><Panel title="Risco por natureza" subtitle="RAID consolidado"><div className="risk-bars">{[["Riscos",7,70],["Impedimentos",4,40],["Premissas",5,50],["Dependências",8,80]].map(([n,v,w])=><span key={n}><small>{n}</small><i><em style={{width:`${w}%`}}/></i><b>{v}</b></span>)}</div></Panel></div><Panel title="Commit Grid · engajamento técnico" subtitle="Atividade válida em bases homologadas · últimos 84 dias"><div className="commit-grid">{commitDays.map(x=><i key={x.i} className={`level-${x.v}`} title={`${x.v*2} commits válidos`}/>)}</div><div className="commit-legend"><span>Menos</span>{[0,1,2,3,4].map(x=><i key={x} className={`level-${x}`}/>)}<span>Mais</span><b>312 commits válidos · 11 colaboradores</b></div></Panel></section>;
}

export function ExecutiveOnePager({projects,notify}){
  return <section className="page foundation-page onepager-page"><div className="onepager-actions"><span>Relatório executivo · atualizado em 11/07/2026 às 21:40</span><button className="ghost" onClick={()=>window.print()}><Printer/>Imprimir</button><button className="primary" onClick={()=>notify("One-page preparado para envio com trilha de auditoria.")}><Envelope/>Compartilhar</button></div><article className="onepager"><header><div><small>INVENTOPS · RELATÓRIO EXECUTIVO</small><h2>Portfólio de Projetos</h2><p>Decisões, riscos e próximos marcos em uma página.</p></div><span><b>68</b><small>HEALTH SCORE</small></span></header><div className="onepage-kpis"><span><small>PROJETOS</small><b>{projects.length}</b><em>2 bloqueados</em></span><span><small>RISCO FINANCEIRO</small><b>R$ 1,8 mi</b><em>exposição estimada</em></span><span><small>GO LIVES 90D</small><b>4</b><em>2 confirmados</em></span><span><small>CAPACIDADE</small><b>117%</b><em>PLC em setembro</em></span></div><section><h3>Leitura executiva</h3><p>A carteira evoluiu 7 pontos em saúde nos últimos 30 dias. O avanço é sustentado por evidências técnicas, mas três dependências ameaçam a previsibilidade: conectividade do Market Peru, ambiente HML do Navepark e capacidade compartilhada de PLC.</p></section><div className="onepage-columns"><section><h3>Decisões solicitadas</h3><ol><li>Autorizar aceleração do hardware TITANO.</li><li>Escalar conectividade Market Peru com o cliente.</li><li>Repriorizar capacidade PLC para agosto e setembro.</li></ol></section><section><h3>Próximos marcos</h3>{projects.slice(0,4).map(p=><div className="onepage-project" key={p.name}><b>{p.name}</b><span>{p.next}</span><em>{p.date}</em></div>)}</section></div><footer><span>Fonte: InventOps · dados auditáveis</span><b>Uso executivo interno</b></footer></article></section>;
}

export function AreasPage(){
  const [selected,setSelected]=useState("Todos"); const shown=selected==="Todos"?departments:departments.filter(d=>d.load>100);
  return <section className="page foundation-page"><div className="area-journey"><div><small>JORNADA CROSS-DEPARTMENT · TITANO</small><h2>14 áreas, uma única verdade operacional</h2><p>Cada etapa mostra progresso, capacidade e bloqueios sem perder a visão horizontal do projeto.</p></div><div className="journey-strip">{departments.map((d,i)=><span className={d.load>100?"over":""} key={d.code}><b>{d.code}</b><small>{i<3?"Concluído":i<10?"Em curso":"Planejado"}</small></span>)}</div></div><div className="area-toolbar"><div><button className={selected==="Todos"?"active":""} onClick={()=>setSelected("Todos")}>Todas as áreas</button><button className={selected==="Sobrecarga"?"active":""} onClick={()=>setSelected("Sobrecarga")}>Sobrecarga</button></div><span><i/> acima de 100% de capacidade</span></div><div className="area-grid">{shown.map(d=><article key={d.code} className={d.load>100?"over":""}><header><span>{d.code}</span><div><b>{d.name}</b><small>{d.owner}</small></div><em>{d.load}%</em></header><div><span><small>PROGRESSO</small><b>{d.progress}%</b></span><i><em style={{width:`${d.progress}%`}}/></i></div><footer><span>{d.blocked} bloqueios ativos</span><b>{d.load>100?"Replanejar":"Capacidade controlada"}</b></footer></article>)}</div></section>;
}

export function RaidPage(){
  const [selected,setSelected]=useState(null); const matrix=useMemo(()=>Array.from({length:25},(_,i)=>({impact:5-Math.floor(i/5),prob:i%5+1})),[]);
  return <section className="page foundation-page"><div className="foundation-metrics"><Metric icon={Warning} label="SCORE CRÍTICO" value="20–25" note="2 itens" tone="red"/><Metric icon={ChartLineUp} label="RAID ATIVO" value="24 itens" note="5 exigem ação" tone="yellow"/><Metric icon={ShieldCheck} label="COM RESPOSTA" value="92%" note="meta ≥ 95%" tone="green"/><Metric icon={ClockCountdown} label="VENCIDOS" value="1" note="Market Peru" tone="red"/></div><div className="foundation-grid raid-layout"><Panel title="Matriz de risco 5 × 5" subtitle="Probabilidade × impacto · clique em um item para abrir"><div className="raid-axis"><span>IMPACTO →</span><div className="raid-matrix">{matrix.map(cell=>{const item=riskItems.find(r=>r.prob===cell.prob&&r.impact===cell.impact);const score=cell.prob*cell.impact;return <button key={`${cell.prob}-${cell.impact}`} className={score>=16?"critical":score>=9?"warning":"low"} onClick={()=>item&&setSelected(item)}><small>{score}</small>{item?<b>{item.id}</b>:null}</button>})}</div><em>PROBABILIDADE →</em></div></Panel><Panel title="RAID prioritário" subtitle="Risco, premissa, impedimento e dependência"><div className="raid-list">{riskItems.map(r=><button key={r.id} onClick={()=>setSelected(r)}><span>{r.id}</span><div><b>{r.title}</b><small>{r.project} · {r.owner}</small></div><em>{r.prob*r.impact}</em></button>)}</div></Panel></div>{selected?<div className="modal-layer" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><article className="raid-modal" role="dialog" aria-modal="true"><header><span>{selected.id}</span><button onClick={()=>setSelected(null)} aria-label="Fechar"><XCircle/></button></header><small>{selected.kind} · {selected.project}</small><h2>{selected.title}</h2><div><span><small>PROBABILIDADE</small><b>{selected.prob}/5</b></span><span><small>IMPACTO</small><b>{selected.impact}/5</b></span><span><small>SCORE</small><b>{selected.prob*selected.impact}/25</b></span></div><dl><div><dt>Responsável</dt><dd>{selected.owner}</dd></div><div><dt>Estratégia</dt><dd>{selected.response}</dd></div><div><dt>Prazo</dt><dd>{selected.due}</dd></div></dl><button className="primary" onClick={()=>setSelected(null)}>Abrir plano de resposta</button></article></div>:null}</section>;
}

export function AdminGovernance({role,setRole,notify}){
  const roles={Admin:[1,1,1,1,1],Editor:[1,1,1,0,0],Analista:[1,1,0,0,0],Viewer:[1,0,0,0,0]};
  const permissions=["Visualizar","Editar operação","Gerenciar projetos","Administrar acessos","Configurar integrações"];
  return <section className="page foundation-page"><div className="admin-banner"><ShieldCheck/><div><small>GOVERNANÇA DE ACESSO</small><h2>Permissão clara, ação auditável</h2><p>A demonstração aplica perfis na interface. Em produção, a mesma regra será validada novamente no servidor.</p></div><span><LockKey/>Sessão ativa</span></div><div className="foundation-grid equal"><Panel title="Simular perfil de acesso" subtitle="Use na apresentação para demonstrar o RBAC"><div className="role-selector">{Object.keys(roles).map(r=><button className={role===r?"active":""} key={r} onClick={()=>{setRole(r);notify(`Perfil alterado para ${r}. A navegação foi recalculada.`)}}><UserGear/><span><b>{r}</b><small>{r==="Admin"?"Controle total":r==="Viewer"?"Somente leitura":"Acesso operacional"}</small></span></button>)}</div></Panel><Panel title="Regras obrigatórias" subtitle="Validações que protegem a qualidade do dado"><ul className="governance-rules"><li><CheckCircle/><span><b>Concluído = 100%</b><small>Sem atraso pendente ou atividade aberta.</small></span></li><li><CheckCircle/><span><b>Bloqueado exige plano</b><small>Categoria, responsável, próxima ação e data.</small></span></li><li><CheckCircle/><span><b>Importação transacional</b><small>Arquivo inválido não altera a base.</small></span></li><li><CheckCircle/><span><b>Link seguro do analista</b><small>Token expirável vinculado a e-mail e tarefa.</small></span></li></ul></Panel></div><Panel title="Matriz de permissões" subtitle="Rotas e ações por perfil"><div className="permission-table"><header><span>Permissão</span>{Object.keys(roles).map(r=><span key={r}>{r}</span>)}</header>{permissions.map((p,i)=><div key={p}><b>{p}</b>{Object.keys(roles).map(r=><span key={r}>{roles[r][i]?<CheckCircle/>:<XCircle/>}</span>)}</div>)}</div></Panel><Panel title="Trilha de auditoria" subtitle="Quem fez o quê, quando e sobre qual registro"><div className="audit-log">{[["21:38","Douglas","Alterou prazo do Go Live","TITANO"],["20:54","Daiana Costa","Anexou evidência REV4","QUELUZ"],["19:42","Sistema IoT","Criou alerta P0","TITANO"],["18:17","Ivan","Atualizou bloqueio de VPN","MARKET PERU"]].map(x=><div key={x.join()}><span>{x[0]}</span><b>{x[1]}</b><p>{x[2]}</p><em>{x[3]}</em></div>)}</div></Panel></section>;
}

export function LifecyclePage(){
  const [horizon,setHorizon]=useState("12 meses");
  const milestones=[
    {version:"V17.3",period:"JUL · 2026",status:"EM CURSO",title:"Controle governado",owner:"PMO + Tecnologia",progress:78,tone:"yellow",value:"Uma carteira única, auditável e explicável.",scope:["Central completa de projetos","14 áreas e 7 fases","Evidências, RAID e Smart Triage"],gate:"Demo validada pela diretoria"},
    {version:"V18",period:"AGO–SET · 2026",status:"PRÓXIMO",title:"Operação conectada",owner:"TI + Dados",progress:24,tone:"cyan",value:"Fim das planilhas paralelas e atualização manual.",scope:["PostgreSQL e APIs reais","SSO Microsoft 365 + RBAC","Importação segura e notificações"],gate:"Base integrada com 3 projetos-piloto"},
    {version:"V19",period:"OUT–DEZ · 2026",status:"PLANEJADO",title:"Inteligência preditiva",owner:"PMO + Genius AI",progress:8,tone:"purple",value:"Decidir antes que o atraso vire custo.",scope:["Simulador de impacto IA","Previsão de gargalos e capacidade","Briefing executivo recomendado"],gate:"Acurácia preditiva ≥ 80%"},
    {version:"V20",period:"JAN–MAR · 2027",status:"VISÃO",title:"Chão de fábrica vivo",owner:"Automação + IoT",progress:0,tone:"green",value:"TI e TA conectadas ao mesmo projeto.",scope:["Telemetria de CLPs e sensores","Gêmeo digital de comissionamento","Falha física gera alerta P0"],gate:"Uma esteira piloto em produção"},
    {version:"V21",period:"ABR–JUN · 2027",status:"NORTH STAR",title:"Operação autônoma assistida",owner:"Diretoria + Operações",progress:0,tone:"blue",value:"O sistema recomenda, orquestra e aprende.",scope:["Workflows automáticos","Playbooks de recuperação","Benchmark de projetos e squads"],gate:"Redução mensurável de atraso e retrabalho"}
  ];
  const visible=horizon==="90 dias"?milestones.slice(0,2):horizon==="6 meses"?milestones.slice(0,3):milestones;
  return <section className="page foundation-page lifecycle-page">
    <div className="release-hero roadmap-hero"><div><small>RELEASE ATUAL</small><span>V17.3</span></div><div><small>INVENTOPS · PRODUCT ROADMAP</small><h2>Da verdade operacional à prevenção automática</h2><p>Um único produto em cinco estágios de maturidade. Primeiro tornamos a operação confiável; depois conectamos dados, prevemos impacto e fechamos o ciclo com o chão de fábrica.</p></div><div className="roadmap-health"><RocketLaunch/><span><b>78%</b><small>ciclo atual</small></span></div></div>
    <div className="roadmap-command"><div><small>HORIZONTE DE DECISÃO</small><div>{["90 dias","6 meses","12 meses"].map(x=><button key={x} className={horizon===x?"active":""} onClick={()=>setHorizon(x)}>{x}</button>)}</div></div><span><CalendarBlank/><small>ÚLTIMA REVISÃO</small><b>12 jul 2026</b></span><span><FlagCheckered/><small>PRÓXIMO GATE</small><b>Demo com diretoria</b></span><span><ShieldCheck/><small>TESE DO PRODUTO</small><b>Controlar → Prever → Agir</b></span></div>
    <div className="roadmap-board">{visible.map((m,i)=><article className={`roadmap-card ${m.tone}`} key={m.version}>
      <header><span>{String(i+1).padStart(2,"0")}</span><div><small>{m.period}</small><b>{m.version}</b></div><em>{m.status}</em></header>
      <div className="roadmap-card-body"><small>ERA ESTRATÉGICA</small><h3>{m.title}</h3><p>{m.value}</p><div className="roadmap-owner"><UsersThree/><span><small>RESPONSÁVEL</small><b>{m.owner}</b></span></div><ul>{m.scope.map(x=><li key={x}><CheckCircle/>{x}</li>)}</ul></div>
      <footer><div><span><small>MATURIDADE</small><b>{m.progress}%</b></span><i><em style={{width:`${m.progress}%`}}/></i></div><p><FlagCheckered/><span><small>CRITÉRIO DE SAÍDA</small><b>{m.gate}</b></span></p></footer>
    </article>)}</div>
    <div className="foundation-grid two-one roadmap-bottom"><Panel title="Valor liberado por etapa" subtitle="O roadmap mede resultado, não apenas funcionalidades"><div className="value-ladder">{[["AGORA","Confiabilidade","Uma fonte oficial para projetos e decisões"],["V18","Eficiência","Menos cobrança manual e retrabalho de relatório"],["V19","Antecipação","Risco traduzido em prazo, capacidade e custo"],["V20+","Autonomia","Falha detectada, priorizada e tratada no fluxo"]].map((x,i)=><div key={x[0]}><span>{i+1}</span><small>{x[0]}</small><b>{x[1]}</b><p>{x[2]}</p></div>)}</div></Panel><Panel title="Governança do roadmap" subtitle="Como uma etapa avança"><div className="roadmap-governance"><p><ShieldCheck/><span><b>Gate executivo</b><small>Patrocínio, prioridade e valor aprovados.</small></span></p><p><Database/><span><b>Gate técnico</b><small>Dados, segurança e integração validados.</small></span></p><p><CheckSquare/><span><b>Gate operacional</b><small>Piloto aceito com evidência e responsável.</small></span></p><button className="primary" onClick={()=>setHorizon("12 meses")}>Ver visão completa<ArrowRight/></button></div></Panel></div>
  </section>;
}

export function PresentationPage({notify}){
  const profiles={
    Analista:{icon:CheckSquare,color:"cyan",promise:"Minha rotina, sem planilhas paralelas.",screens:["Ação","Projetos · Atividades","Evidências"],focus:["Demandas vinculadas ao perfil","Prazo, evidência e status","E-mail corporativo preparado"],script:"Para o analista, o InventOps centraliza a rotina e elimina planilhas paralelas. Cada demanda chega vinculada ao perfil corporativo, com prazo, evidência esperada e contexto do projeto. O analista atualiza a execução e transforma trabalho técnico em progresso confiável."},
    Gestor:{icon:UsersThree,color:"yellow",promise:"Distribuir, cobrar e desbloquear com contexto.",screens:["Controle de Projetos","Áreas Técnicas","Matriz RAID"],focus:["Capacidade e responsáveis","Bloqueios com plano obrigatório","Status Report em um clique"],script:"Para o gestor, o InventOps reúne distribuição de trabalho, capacidade e riscos. Em poucos cliques, ele vincula a tarefa ao e-mail corporativo do colaborador, acompanha o prazo e prepara cobranças ou Status Reports para WhatsApp e Outlook."},
    Diretor:{icon:ChartLineUp,color:"purple",promise:"Decidir antes que o atraso vire custo.",screens:["Dashboard Executivo","Simulador de Impacto","Releases & Roadmap"],focus:["Health Score e decisões do dia","Cenários de prazo e capacidade","Evolução do produto por valor"],script:"Para a diretoria, o InventOps traduz a carteira em decisões. O dashboard aponta onde agir hoje, o simulador antecipa impactos entre projetos e o roadmap mostra como a plataforma evolui do controle governado para a prevenção automática no chão de fábrica."}
  };
  const [selected,setSelected]=useState("Diretor");
  const current=profiles[selected]; const Icon=current.icon;
  const copy=async()=>{try{await navigator.clipboard.writeText(current.script)}catch{}notify(`Roteiro ${selected} copiado para gravação ou ElevenLabs.`)};
  return <section className="page foundation-page presentation-page"><div className="presentation-hero"><div><small>MODO APRESENTAÇÃO · DIRETORIA</small><h2>Um produto. Três níveis de valor.</h2><p>Roteiro visual pronto para demonstrar o InventOps pelo ponto de vista de quem executa, de quem coordena e de quem decide.</p></div><span><Play weight="fill"/><b>≈ 3 min</b><small>roteiro completo</small></span></div><div className="presentation-profiles">{Object.entries(profiles).map(([name,item])=>{const RoleIcon=item.icon;return <button key={name} className={`${selected===name?"active":""} ${item.color}`} onClick={()=>setSelected(name)}><RoleIcon/><span><small>VISÃO</small><b>{name}</b><p>{item.promise}</p></span><em>{selected===name?"Selecionado":"Abrir"}</em></button>})}</div><div className="presentation-stage"><article><header><span className={current.color}><Icon/></span><div><small>ROTEIRO · {selected.toUpperCase()}</small><h3>{current.promise}</h3></div><button className="primary" onClick={copy}><ClipboardText/>Copiar narração</button></header><div className="presentation-route">{current.screens.map((screen,i)=><div key={screen}><span>{i+1}</span><div><small>TELA {i+1}</small><b>{screen}</b><p>{current.focus[i]}</p></div>{i<current.screens.length-1?<ArrowRight/>:null}</div>)}</div><blockquote>“{current.script}”</blockquote></article><aside><small>GUIA DE GRAVAÇÃO</small><h3>Direto, real e sem promessas falsas</h3><ul><li><CheckCircle/>Gravar as telas reais do InventOps.</li><li><CheckCircle/>Usar os perfis Analista, Gestor e Diretor.</li><li><CheckCircle/>Mostrar Outlook e WhatsApp como preparação para envio.</li><li><CheckCircle/>Encerrar com o Roadmap V17.3 → V21.</li></ul><div><ShieldCheck/><span><b>Branding oficial</b><small>Nome InventOps confirmado por Daiana. Logo final depende da validação do Marketing.</small></span></div></aside></div></section>;
}

export function LoginScreen({onLogin}){
  const [email,setEmail]=useState("douglas.alves@invent-corp.com"); const [password,setPassword]=useState("inventops2026"); const [showDemo,setShowDemo]=useState(false);
  const submit=e=>{e.preventDefault();if(email&&password)onLogin(email)};
  return <main className="login-screen"><div className="login-visual"><div className="login-brand"><img src={`${import.meta.env.BASE_URL}assets/icon.svg`} alt="InventOps"/><span><b>Invent<span>Ops</span></b><small>OPERATIONS INTELLIGENCE</small></span></div><div className="login-message"><small>CONTROLE · EVIDÊNCIA · PREVISÃO</small><h1>A operação inteira.<br/><span>Uma única verdade.</span></h1><p>Centralize projetos, conecte áreas e antecipe gargalos antes que eles cheguem ao chão de fábrica.</p></div><div className="login-pulse"><span><Factory/><b>14</b><small>áreas conectadas</small></span><span><ChartLineUp/><b>68</b><small>health score</small></span><span><Sparkle/><b>IA</b><small>impacto preditivo</small></span></div><footer>InventOps Predictive Twin · V17</footer></div><section className="login-panel"><form onSubmit={submit}><div className="login-mobile-brand"><img src={`${import.meta.env.BASE_URL}assets/icon.svg`} alt=""/><b>Invent<span>Ops</span></b></div><small>ACESSO SEGURO</small><h2>Bem-vindo ao InventOps</h2><p>Entre com sua conta corporativa para acessar sua visão da operação.</p><label>E-mail corporativo<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoFocus/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="login-options"><label><input type="checkbox"/> Manter sessão neste dispositivo</label><button type="button" onClick={()=>setShowDemo(!showDemo)}>Acessos da demo</button></div>{showDemo?<div className="demo-credentials"><b>Perfis disponíveis após entrar</b><span>Admin · Editor · Analista · Viewer</span><small>Ambiente demonstrativo — sem credenciais reais.</small></div>:null}<button className="primary" type="submit">Entrar no InventOps<ArrowRight/></button><div className="sso-divider"><span>ou</span></div><button className="sso-button" type="button" onClick={()=>onLogin("douglas.alves@invent-corp.com")}><span>M</span>Continuar com Microsoft 365</button><footer><ShieldCheck/>Sessão protegida · acesso auditável</footer></form></section></main>;
}

export function StatusReportModal({project,onClose,notify}){
  const text=`📊 STATUS REPORT — ${project.name}\n🟡 Saúde: ${project.health}/100 · Progresso: ${project.progress}%\n📍 Fase atual: ${project.phase}/7\n🚩 Próximo marco: ${project.next} — ${project.date}\n⚠️ Ponto de atenção: ${project.blocker}\n✅ Próxima ação: ${project.nextAction}\n👤 Responsável: ${project.owner}`;
  const email=project.ownerEmail||`${(project.owner||"responsavel").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().replace(/\s+/g,".")}@invent-corp.com`;
  const register=channel=>notify(`Status Report preparado para ${channel} e registrado no histórico de comunicações.`);
  const copy=async()=>{try{await navigator.clipboard.writeText(text)}catch{}register("cópia")};
  const whatsapp=()=>{window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");register("WhatsApp")};
  const mail=()=>{const subject=`InventOps · Status Report · ${project.name}`;window.location.href=`mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text)}`;register("e-mail corporativo")};
  return <div className="modal-layer" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><article className="status-report-modal communication-modal" role="dialog" aria-modal="true"><header><div><small>CENTRAL DE COMUNICAÇÃO</small><h2>Status Report · {project.name}</h2><p>Revise o conteúdo e escolha como deseja compartilhar.</p></div><button onClick={onClose} aria-label="Fechar"><XCircle/></button></header><pre>{text}</pre><div className="communication-recipient"><Envelope/><span><small>DESTINATÁRIO VINCULADO</small><b>{email}</b></span><em>Corporativo</em></div><div className="communication-actions"><button className="ghost" onClick={copy}><ClipboardText/>Copiar texto</button><button className="whatsapp" onClick={whatsapp}><WhatsappLogo/>Abrir WhatsApp</button><button className="primary" onClick={mail}><Envelope/>Abrir no Outlook</button></div><footer><ShieldCheck/>A demo prepara a comunicação. O usuário revisa e confirma o envio no aplicativo escolhido.</footer></article></div>;
}

export function AccessDenied({setActive}){
  return <section className="page access-denied"><LockKey/><small>ACESSO RESTRITO · 403</small><h2>Este perfil não pode acessar este módulo.</h2><p>A política de acesso foi aplicada antes da abertura da página. Solicite permissão a um administrador ou retorne ao dashboard.</p><button className="primary" onClick={()=>setActive("home")}>Voltar ao Dashboard</button></section>;
}
